Repository TeamNado-Sunbae/NadoSunbae-Server, pull requests merged in 2022-01, with the labels that each got.

#34 [FEAT] #2 - authSignupPOST
  functions/api/routes/auth/authSignupPOST.js
  functions/api/routes/auth/index.js
  functions/api/routes/index.js
  functions/constants/responseMessage.js
  functions/db/index.js
  functions/db/user.js
  functions/lib/jwtHandlers.js
Labels: enhancement, 🌺 eunji

#32 [FEAT] #3 - authDuplicationCheckNicknamePOST
  functions/api/routes/auth/authDuplicationCheckNicknamePOST.js
  functions/api/routes/auth/index.js
  functions/api/routes/index.js
  functions/constants/responseMessage.js
  functions/constants/statusCode.js
  functions/db/index.js
  functions/db/user.js
Labels: enhancement, ❄️ seol

#35 [FEAT] #6 - majorGET
  functions/api/routes/index.js
  functions/api/routes/major/index.js
  functions/api/routes/major/majorGET.js
  functions/constants/responseMessage.js
  functions/db/index.js
  functions/db/major.js
Labels: enhancement, 🦊 juhyeon

#38 [FIX] #6 - majorGET 쿼리문 수정 및 함수명 수정
  functions/api/routes/major/majorGET.js
  functions/db/major.js
Labels: bug, 🦊 juhyeon

#37 [FEAT] #10 - reviewPostPOST
  functions/api/routes/index.js
  functions/api/routes/reviewPost/index.js
  functions/api/routes/reviewPost/reviewPostPOST.js
  functions/constants/responseMessage.js
  functions/constants/reviewPostContent.js
  functions/db/image.js
  functions/db/index.js
  functions/db/major.js
  functions/db/relationReviewPostTag.js
  functions/db/reviewPost.js
  functions/db/tag.js
  functions/db/user.js
  functions/middlewares/auth.js
Labels: enhancement, ❄️ seol

#40 [FEAT] #5 - authLogin
  functions/api/routes/auth/authDuplicationCheckNicknamePOST.js
  functions/api/routes/auth/authLoginPOST.js
  functions/api/routes/auth/index.js
  functions/db/major.js
  functions/db/user.js
Labels: enhancement, 🦊 juhyeon

#41 [FEAT] #15 - reviewPostBackgroundImageListGET
  functions/api/routes/major/majorListGET.js
  functions/api/routes/reviewPost/index.js
  functions/api/routes/reviewPost/reviewPostBackgroundImageListGET.js
  functions/constants/responseMessage.js
  functions/db/image.js
Labels: enhancement, 🦊 juhyeon

#44 [FEAT] # 19 classroomPostPOST
  functions/api/routes/classroomPost/classroomPostPOST.js
  functions/api/routes/classroomPost/index.js
  functions/api/routes/index.js
  functions/api/routes/reviewPost/index.js
  functions/api/routes/reviewPost/reviewPostDetailGET.js
  functions/api/routes/reviewPost/reviewPostTagListGET.js
  functions/constants/responseMessage.js
  functions/db/classroomPost.js
  functions/db/index.js
  functions/db/like.js
  functions/db/major.js
  functions/db/reviewPost.js
  functions/db/tag.js
  functions/db/user.js
Labels: enhancement, 🌺 eunji

#53 [FIX] #19 classroomPostPOST
  functions/api/routes/classroomPost/classroomPostPOST.js
Labels: bug, 🌺 eunji

#46 [FEAT] #18 - classroomPostInformaionGET
  functions/api/routes/classroomPost/classroomPostInformationGET.js
  functions/api/routes/classroomPost/index.js
  functions/api/routes/index.js
  functions/constants/responseMessage.js
  functions/db/classroomPost.js
  functions/db/comment.js
  functions/db/index.js
  functions/db/like.js
  functions/db/postType.js
Labels: enhancement, ❄️ seol

#36 [FEAT] #9 - reviewPostDetailGET
  functions/api/routes/reviewPost/reviewPostDetailGET.js
  functions/db/image.js
  functions/db/like.js
  functions/db/reviewPost.js
Labels: enhancement, 🌺 eunji

#39 [FEAT] #14 reviewPostTagListGET
  functions/api/routes/reviewPost/index.js
  functions/api/routes/reviewPost/reviewPostDetailGET.js
  functions/api/routes/reviewPost/reviewPostTagListGET.js
  functions/db/reviewPost.js
Labels: enhancement, 🌺 eunji

#45 [FEAT] #16 - userListMajorGET
  functions/api/routes/index.js
  functions/api/routes/user/index.js
  functions/api/routes/user/userListMajorGET.js
  functions/db/user.js
Labels: enhancement, ❄️ seol

#64 [FEAT] #26 userMypageUserGET
  functions/api/routes/index.js
  functions/api/routes/user/index.js
  functions/api/routes/user/userMypageUserGET.js
Labels: enhancement, 🌺 eunji

#48 [FEAT] #31 - reportUserPOST
  functions/api/routes/index.js
  functions/api/routes/report/index.js
  functions/api/routes/report/reportUserPOST.js
  functions/constants/responseMessage.js
  functions/db/user.js
Labels: enhancement, ❄️ seol

#52 [FEAT] #30 - reportCommentPOST
  functions/api/routes/report/index.js
  functions/api/routes/report/reportCommentPOST.js
  functions/db/comment.js
Labels: enhancement, 🦊 juhyeon

#54 [FEAT] #25 - likePOST
  functions/api/routes/index.js
  functions/api/routes/like/index.js
  functions/api/routes/like/likePOST.js
  functions/constants/responseMessage.js
  functions/db/like.js
Labels: enhancement, 🦊 juhyeon

#55 [FEAT] #27 - userMypageClassroomPostListGET
  functions/api/routes/index.js
  functions/api/routes/user/index.js
  functions/api/routes/user/userMypageClassroomPostListGET.js
  functions/db/classroomPost.js
  functions/db/comment.js
  functions/db/like.js
Labels: enhancement, ❄️ seol

#56 [FEAT] #24 - commentDELETE
  functions/api/routes/comment/commentDELETE.js
  functions/api/routes/comment/index.js
  functions/api/routes/index.js
  functions/constants/responseMessage.js
  functions/db/comment.js
Labels: enhancement, 🦊 juhyeon

#57 [FEAT] #11 - reviewPostPUT
  functions/api/routes/reviewPost/index.js
  functions/api/routes/reviewPost/reviewPostPUT.js
  functions/db/reviewPost.js
Labels: enhancement, 🦊 juhyeon

#63 [FIX] #62 - majorGET rows -> rows[0] 수정
  functions/db/major.js
Labels: bug, 🦊 juhyeon

#67 [FIX] #67 - prevent no post from reading
  functions/api/routes/classroomPost/classroomPostInformationGET.js
Labels: bug, ❄️ seol

#50 [FEAT] #21 classroomPostDELETE
  functions/api/routes/classroomPost/classroomPostDELETE.js
  functions/api/routes/classroomPost/index.js
  functions/constants/responseMessage.js
  functions/db/classroomPost.js
  functions/db/comment.js
Labels: enhancement, 🌺 eunji

#72 [FIX] 태그 필터 순서 변경
  functions/api/routes/reviewPost/reviewPostDetailGET.js
  functions/api/routes/reviewPost/reviewPostPOST.js
  functions/api/routes/reviewPost/reviewPostPUT.js
  functions/db/reviewPost.js
Labels: bug, 🦊 juhyeon

#43 [FEAT] #12 - reviewPostDELETE
  functions/api/routes/reviewPost/index.js
  functions/api/routes/reviewPost/reviewPostDELETE.js
  functions/constants/responseMessage.js
  functions/db/relationReviewPostTag.js
  functions/db/reviewPost.js
Labels: enhancement, ❄️ seol

#47 [FEAT] #23 - commentPUT
  functions/api/routes/comment/commentPUT.js
  functions/api/routes/comment/index.js
  functions/constants/responseMessage.js
  functions/db/comment.js
Labels: enhancement, ❄️ seol

#51 [FEAT] #22 commentPOST
  functions/api/routes/comment/commentPOST.js
  functions/api/routes/comment/index.js
  functions/db/comment.js
Labels: enhancement, 🌺 eunji

#58 [FEAT] #17 - classroomPostMajorListGET
  functions/api/routes/classroomPost/classroomPostMajorListGET.js
  functions/api/routes/classroomPost/index.js
  functions/constants/responseMessage.js
  functions/db/classroomPost.js
Labels: enhancement, 🦊 juhyeon

#65 [FEAT] #29 reportPostPOST
  functions/api/routes/report/index.js
  functions/api/routes/report/reportPostPOST.js
  functions/db/classroomPost.js
  functions/db/reviewPost.js
Labels: enhancement, 🌺 eunji

#73 [FEAT] #20 classroomPostPUT
  functions/api/routes/classroomPost/classroomPostPUT.js
  functions/api/routes/classroomPost/index.js
  functions/db/classroomPost.js
Labels: enhancement, 🌺 eunji

#75 [FIX] modify function name
  functions/api/routes/classroomPost/classroomPostPOST.js
  functions/db/classroomPost.js
Labels: bug, 🌺 eunji

#59 [FEAT] #8 reviewPostListPOST
  functions/api/routes/reviewPost/index.js
  functions/api/routes/reviewPost/reviewPostListPOST.js
  functions/db/relationReviewPostTag.js
  functions/db/reviewPost.js
Labels: enhancement, 🦊 juhyeon

#61 [FIX] #60 - majorListGET 이중 전공 리스트 가져올 때 제1전공 false로 가져오던 오류 수정
  functions/api/routes/major/majorListGET.js
  functions/db/major.js
Labels: bug, 🦊 juhyeon

#70 [FEAT] #66 - reviewPostPUT에 relationReviewPostTag 수정 기능 추가
  functions/api/routes/reviewPost/reviewPostPUT.js
  functions/constants/responseMessage.js
  functions/db/relationReviewPostTag.js
Labels: enhancement, 🦊 juhyeon

#69 [FEAT] #42 - classroomPostQuestionGET
  functions/api/routes/classroomPost/classroomPostQuestionGET.js
  functions/api/routes/classroomPost/index.js
Labels: enhancement, ❄️ seol

#77 [FIX] change functions name to resolve conflicts
  functions/api/routes/reviewPost/reviewPostPUT.js
  functions/db/relationReviewPostTag.js
Labels: bug, 🦊 juhyeon

#78 [FEAT] #74 profile_image_id random generation
  functions/api/routes/auth/authSignupPOST.js
  functions/db/user.js
  functions/package-lock.json
  functions/package.json
Labels: enhancement, 🌺 eunji

#79 [FIX] add id to postType
  functions/api/routes/classroomPost/classroomPostQuestionGET.js
Labels: bug, ❄️ seol

#81 [FEAT] #4 - authDuplicationCheckEmailPOST
  functions/api/routes/auth/authDuplicationCheckEmailPOST.js
  functions/api/routes/auth/index.js
  functions/constants/responseMessage.js
  functions/db/user.js
Labels: enhancement, 🦊 juhyeon

#83 [FEAT] #82 - login에 device token 업데이트 추가
  functions/api/routes/auth/authLoginPOST.js
  functions/constants/responseMessage.js
  functions/db/user.js
Labels: enhancement, 🦊 juhyeon

#86 [FEAT] #84 - login 리스폰스에 major id 추가
  functions/api/routes/auth/authLoginPOST.js
Labels: enhancement, 🦊 juhyeon

#91 [FEAT] #80 - push alarm
  functions/api/routes/classroomPost/classroomPostPOST.js
  functions/api/routes/comment/commentPOST.js
  functions/constants/notificationType.js
  functions/constants/postType.js
  functions/constants/responseMessage.js
  functions/db/index.js
  functions/db/notification.js
  functions/db/user.js
  package-lock.json
Labels: enhancement, ❄️ seol

#95 [FEAT] #87 - authLoginToken
  functions/api/routes/auth/authLoginTokenPOST.js
  functions/api/routes/auth/index.js
Labels: enhancement, 🦊 juhyeon

#92 [FEAT] #88 - notificationListGET
  functions/api/routes/index.js
  functions/api/routes/notification/index.js
  functions/api/routes/notification/notificationListGET.js
Labels: enhancement, ❄️ seol

#93 [FEAT]#89 - notificationReadPUT
  functions/api/routes/notification/notificationReadPUT.js
Labels: enhancement, ❄️ seol

#94 [FEAT] #90 - notificationDELETE
  functions/api/routes/notification/notificationDELETE.js
  functions/constants/responseMessage.js
Labels: enhancement, ❄️ seol

#99 [FIX] edit comment list query order by create date
  functions/db/comment.js
Labels: enhancement, 🦊 juhyeon

#104 [FIX] #103 - commentPOST 푸시알림 multicast error
  functions/api/routes/comment/commentPOST.js
Labels: bug, 🦊 juhyeon

#105 [FIX] #103 - 푸시 알림 multicast error
  functions/api/routes/comment/commentPOST.js
Labels: bug, 🦊 juhyeon

#107 [FIX] #106 - sort filter query to body
  functions/api/routes/reviewPost/reviewPostListPOST.js
Labels: bug, 🦊 juhyeon

#110 [FIX] #109 - 후기 목록 가져올 때 postid 오류 수정
  functions/api/routes/reviewPost/reviewPostListPOST.js
Labels: bug, 🦊 juhyeon

#121 [FEAT] #120 middleware에 slackAPI 추가
  functions/middlewares/slackAPI.js
Labels: enhancement, 🌺 eunji

#123 [FEAT] #112 add SlackAPI to classroomPost/
  functions/api/routes/classroomPost/classroomPostDELETE.js
  functions/api/routes/classroomPost/classroomPostInformationGET.js
  functions/api/routes/classroomPost/classroomPostMajorListGET.js
  functions/api/routes/classroomPost/classroomPostPOST.js
  functions/api/routes/classroomPost/classroomPostPUT.js
  functions/api/routes/classroomPost/classroomPostQuestionGET.js
Labels: enhancement, 🌺 eunji

#126 [FEAT] # 114 add SlackAPI to like/
  functions/api/routes/like/likePOST.js
Labels: enhancement, 🌺 eunji

#124 [FEAT] #113 add SlackAPI to comment/
  functions/api/routes/comment/commentDELETE.js
  functions/api/routes/comment/commentPOST.js
  functions/api/routes/comment/commentPUT.js
Labels: enhancement, 🌺 eunji

#125 [FEAT] #122 - mypage, other mypage 분리 및 like count, review post count 추가
  functions/api/routes/user/index.js
  functions/api/routes/user/userMypageGET.js
  functions/api/routes/user/userMypageOtherGET.js
  functions/db/like.js
  functions/db/reviewPost.js
Labels: enhancement, ❄️ seol

#127 [FEAT] #115 add SlackAPI to major/
  functions/api/routes/major/majorGET.js
  functions/api/routes/major/majorListGET.js
Labels: enhancement, 🌺 eunji

#128 [FEAT] #116 add SlackAPI to notification/
  functions/api/routes/notification/notificationDELETE.js
  functions/api/routes/notification/notificationListGET.js
  functions/api/routes/notification/notificationReadPUT.js
Labels: enhancement, 🌺 eunji

#129 [FEAT] #117 add SlackAPI to report/
  functions/api/routes/report/reportCommentPOST.js
  functions/api/routes/report/reportPostPOST.js
  functions/api/routes/report/reportUserPOST.js
Labels: enhancement, 🌺 eunji

#130 [FEAT] #118 add SlackAPI to reviewPost/
  functions/api/routes/reviewPost/reviewPostBackgroundImageListGET.js
  functions/api/routes/reviewPost/reviewPostDELETE.js
  functions/api/routes/reviewPost/reviewPostDetailGET.js
  functions/api/routes/reviewPost/reviewPostListPOST.js
  functions/api/routes/reviewPost/reviewPostPOST.js
  functions/api/routes/reviewPost/reviewPostPUT.js
  functions/api/routes/reviewPost/reviewPostTagListGET.js
Labels: enhancement, 🌺 eunji

#131 [FEAT] #119 add SlackAPI to user/
  functions/api/routes/user/userListMajorGET.js
  functions/api/routes/user/userMypageClassroomPostListGET.js
  functions/api/routes/user/userMypageGET.js
  functions/api/routes/user/userMypageOtherGET.js
Labels: enhancement, 🌺 eunji

#139 [FEAT] #138 - 알림 리스트 가져올 때 최신순 정렬 쿼리 추가
  functions/db/notification.js
Labels: enhancement, 🦊 juhyeon

#136 [FIX] add error handling when creating review post
  functions/api/routes/reviewPost/reviewPostPOST.js
  functions/db/user.js
Labels: enhancement, ❄️ seol

#141 [FIX] fix count to number type
  functions/api/routes/classroomPost/classroomPostInformationGET.js
  functions/api/routes/classroomPost/classroomPostMajorListGET.js
  functions/api/routes/classroomPost/classroomPostPUT.js
  functions/api/routes/classroomPost/classroomPostQuestionGET.js
Labels: bug, ❄️ seol

#142 [FIX] #140 fix likeCount to integer value
  functions/api/routes/reviewPost/reviewPostDetailGET.js
  functions/api/routes/reviewPost/reviewPostListPOST.js
  functions/api/routes/reviewPost/reviewPostPUT.js
Labels: bug, 🌺 eunji

#146 [FEAT] #145 - 푸시알림에 소리 추가
  functions/api/routes/classroomPost/classroomPostPOST.js
  functions/api/routes/comment/commentPOST.js
Labels: enhancement, 🦊 juhyeon

#148 [FIX] #147 - fix like sort - change string to int
  functions/api/routes/classroomPost/classroomPostMajorListGET.js
  functions/api/routes/reviewPost/reviewPostListPOST.js
  functions/api/routes/user/userMypageClassroomPostListGET.js
Labels: bug, 🦊 juhyeon
