Repository TeamNado-Sunbae/NadoSunbae-Server, pull requests merged in 2022-10, with the labels that each got.

#385 hide firebase key
  functions/api/routes/post/index.js
  functions/config/firebaseClient.js
  functions/package.json
Labels: refactor

#391 fix qa
  functions/api/routes/notification/notificationListGET.js
  functions/constants/type.js
  functions/lib/jwtHandlers.js
Labels: fix

#392 feat: add is authorized
  functions/api/routes/user/userPostQuestionListGET.js
  functions/db/post.js
Labels: feat

#393 fix: delete bio null exception
  functions/api/routes/user/userPUT.js
Labels: fix

#396 fix: slack alert only when production env
  functions/middlewares/slackAPI.js
Labels: fix

#395 [FIX] fix 1:1 push alarm
  functions/api/routes/comment/commentPOST.js
Labels: fix

#394 [CHORE] change access token expiresIn
  functions/lib/jwtHandlers.js
Labels: fix
