Repository TeamNado-Sunbae/NadoSunbae-Server, pull requests merged in 2022-03, with the labels that each got.

#272 [FIX] #271 - fix authSecessionDELETE to authSecessionPOST
  functions/api/routes/auth/authSecessionPOST.js
  functions/api/routes/auth/index.js
Labels: bug, 🌺 eunji

#276 [FIX] #275 - authLoginPOST에 예외 처리 추가
  functions/api/routes/auth/authLoginPOST.js
Labels: bug, 🌺 eunji

#274 [FEAT] authLoginTokenPOST 구현
  functions/api/routes/auth/authRenewalTokenPOST.js
  functions/api/routes/auth/index.js
  functions/constants/responseMessage.js
  functions/db/user.js
Labels: enhancement, 🦊 juhyeon

#245 [FEAT] #204 - 로그인 시 해당 유저가 이메일 인증 안했을 경우 처리
  functions/api/routes/auth/authLoginPOST.js
  functions/constants/responseMessage.js
  functions/constants/statusCode.js
Labels: enhancement, 🦊 juhyeon

#278 [FIX] fix to get all my like list
  functions/db/classroomPost.js
  functions/db/reviewPost.js
Labels: bug, 🌺 eunji

#285 [FIX] remove deviceToken
  functions/api/routes/auth/authLogoutPOST.js
  functions/db/user.js
Labels: bug, 🦊 juhyeon

#287 [FIX] #286 - fix bug at report code
  functions/api/routes/classroomPost/classroomPostInformationGET.js
  functions/api/routes/classroomPost/classroomPostPOST.js
  functions/api/routes/classroomPost/classroomPostQuestionGET.js
  functions/api/routes/reviewPost/reviewPostDetailGET.js
  functions/api/routes/reviewPost/reviewPostPOST.js
Labels: bug, 🌺 eunji

#289 [REFACTOR] refactor response message
  functions/api/routes/classroomPost/classroomPostMajorListGET.js
  functions/api/routes/report/reportPUT.js
  functions/api/routes/reviewPost/reviewPostDELETE.js
  functions/api/routes/reviewPost/reviewPostPUT.js
  functions/api/routes/user/userMypageClassroomPostListGET.js
  functions/constants/responseMessage.js
Labels: ❄️ seol, refactor

#283 [REFACTOR] 삭제 관련 에러 처리 수정, 각종 컨벤션 통일
  functions/api/routes/classroomPost/classroomPostDELETE.js
  functions/api/routes/comment/commentPUT.js
  functions/api/routes/notification/notificationReadPUT.js
  functions/api/routes/reviewPost/reviewPostDELETE.js
  functions/db/comment.js
  functions/db/notification.js
Labels: 🌺 eunji, refactor

#290 [DELETE] 안 쓰는 모듈, 라이브러리 삭제
  functions/api/routes/classroomPost/classroomPostInformationGET.js
  functions/api/routes/classroomPost/classroomPostPOST.js
  functions/api/routes/classroomPost/classroomPostQuestionGET.js
  functions/api/routes/reviewPost/reviewPostDetailGET.js
  functions/api/routes/reviewPost/reviewPostPOST.js
  functions/constants/responseMessage.js
Labels: 🌺 eunji, refactor
