Repository TeamNado-Sunbae/NadoSunbae-Server, pull requests merged in 2022-08, with the labels that each got.

#299 refactor naming
  functions/api/index.js
  functions/api/routes/auth/authLoginPOST.js
  functions/api/routes/auth/authRenewalTokenPOST.js
  functions/api/routes/auth/authSecessionPOST.js
  functions/api/routes/auth/authSignupPOST.js
  functions/api/routes/auth/index.js
  functions/api/routes/classroomPost/classroomPostInformationGET.js
  functions/api/routes/classroomPost/index.js
  functions/api/routes/comment/commentPOST.js
  functions/api/routes/inappropriateReview/inappropriateReviewPOST.js
  functions/api/routes/inappropriateReview/index.js
  functions/api/routes/index.js
  functions/api/routes/notification/notificationListGET.js
  functions/api/routes/post/index.js
  functions/api/routes/post/postDELETE.js
  functions/api/routes/post/postGET.js
  functions/api/routes/post/postMajorListGET.js
  functions/api/routes/post/postPOST.js
  functions/api/routes/post/postPUT.js
  functions/api/routes/report/reportPOST.js
  functions/api/routes/report/reportPUT.js
  functions/api/routes/review/index.js
  functions/api/routes/review/reviewDELETE.js
  functions/api/routes/review/reviewDetailGET.js
  functions/api/routes/review/reviewListPOST.js
  functions/api/routes/review/reviewPOST.js
  functions/api/routes/review/reviewPUT.js
  functions/api/routes/review/reviewTagListGET.js
  functions/api/routes/reviewPost/index.js
  functions/api/routes/reviewPost/reviewPostTagListGET.js
  functions/api/routes/user/index.js
  functions/api/routes/user/userListMajorGET.js
  functions/api/routes/user/userMypageClassroomPostQuestionListGET.js
  functions/api/routes/user/userMypageCommentListGET.js
  functions/api/routes/user/userMypageGET.js
  functions/api/routes/user/userMypageLikeListGET.js
  functions/api/routes/user/userMypagePostListGET.js
  functions/api/routes/user/userMypagePostQuestionListGET.js
  functions/api/routes/user/userMypageReviewListGET.js
  functions/constants/reportType.js
  functions/constants/responseMessage.js
  functions/constants/reviewContent.js
  functions/db/comment.js
  functions/db/db.js
  functions/db/inappropriateReview.js
  functions/db/index.js
  functions/db/like.js
  functions/db/post.js
  functions/db/relationReviewTag.js
  functions/db/review.js
  functions/lib/jwtHandlers.js
  functions/lib/pushAlarmHandlers.js
  functions/middlewares/auth.js
  functions/middlewares/slackAPI.js
Labels: refactor

#306 refactor: fix routing
  functions/api/routes/block/index.js
  functions/api/routes/major/index.js
  functions/api/routes/notification/index.js
  functions/api/routes/post/index.js
  functions/api/routes/review/index.js
  functions/api/routes/user/index.js
Labels: refactor

#309 no slack alerts in local env, add env to message
  functions/middlewares/slackAPI.js
Labels: fix

#319 check process.env.NODE_ENV
  .firebaserc
  .gitignore
  functions/middlewares/slackAPI.js
  functions/package.json
Labels: fix

#320 define review and post, refactor type and filter
  functions/api/routes/auth/authLoginPOST.js
  functions/api/routes/auth/authRenewalTokenPOST.js
  functions/api/routes/comment/commentPOST.js
  functions/api/routes/inappropriateReview/inappropriateReviewPOST.js
  functions/api/routes/like/likePOST.js
  functions/api/routes/notification/index.js
  functions/api/routes/notification/notificationDELETE.js
  functions/api/routes/notification/notificationListGET.js
  functions/api/routes/post/index.js
  functions/api/routes/post/postGET.js
  functions/api/routes/post/postMajorListGET.js
  functions/api/routes/post/postPOST.js
  functions/api/routes/post/postPUT.js
  functions/api/routes/report/reportPOST.js
  functions/api/routes/report/reportPUT.js
  functions/api/routes/review/reviewDELETE.js
  functions/api/routes/review/reviewDetailGET.js
  functions/api/routes/review/reviewListPOST.js
  functions/api/routes/review/reviewPOST.js
  functions/api/routes/review/reviewPUT.js
  functions/api/routes/review/reviewTagListGET.js
  functions/api/routes/user/index.js
  functions/api/routes/user/userMypageCommentListGET.js
  functions/api/routes/user/userMypageGET.js
  functions/api/routes/user/userMypageLikeListGET.js
  functions/api/routes/user/userMypagePostListGET.js
  functions/api/routes/user/userMypagePostQuestionListGET.js
  functions/api/routes/user/userMypageReviewListGET.js
  functions/constants/notificationType.js
  functions/constants/postType.js
  functions/constants/reportPeriod.js
  functions/constants/reportType.js
  functions/constants/type.js
  functions/db/comment.js
  functions/db/inappropriateReview.js
  functions/db/like.js
  functions/db/post.js
  functions/db/relationReviewTag.js
  functions/db/report.js
  functions/db/review.js
Labels: refactor

#328 errorHandler
  functions/api/routes/app/appLinkGET.js
  functions/api/routes/auth/authCertificationEmailPOST.js
  functions/api/routes/auth/authDuplicationCheckEmailPOST.js
  functions/api/routes/auth/authDuplicationCheckNicknamePOST.js
  functions/api/routes/auth/authLoginPOST.js
  functions/api/routes/auth/authLogoutPOST.js
  functions/api/routes/auth/authRenewalTokenPOST.js
  functions/api/routes/auth/authResetPasswordPOST.js
  functions/api/routes/auth/authSecessionPOST.js
  functions/api/routes/auth/authSignupPOST.js
  functions/api/routes/auth/authUniversityGET.js
  functions/api/routes/block/blockListGET.js
  functions/api/routes/block/blockPOST.js
  functions/api/routes/comment/commentDELETE.js
  functions/api/routes/comment/commentPOST.js
  functions/api/routes/comment/commentPUT.js
  functions/api/routes/inappropriateReview/inappropriateReviewPOST.js
  functions/api/routes/like/likePOST.js
  functions/api/routes/major/majorGET.js
  functions/api/routes/major/majorListGET.js
  functions/api/routes/notification/notificationDELETE.js
  functions/api/routes/notification/notificationListGET.js
  functions/api/routes/notification/notificationReadPUT.js
  functions/api/routes/post/postDELETE.js
  functions/api/routes/post/postGET.js
  functions/api/routes/post/postMajorListGET.js
  functions/api/routes/post/postPOST.js
  functions/api/routes/post/postPUT.js
  functions/api/routes/report/reportPOST.js
  functions/api/routes/report/reportPUT.js
  functions/api/routes/review/reviewDELETE.js
  functions/api/routes/review/reviewDetailGET.js
  functions/api/routes/review/reviewListPOST.js
  functions/api/routes/review/reviewPOST.js
  functions/api/routes/review/reviewPUT.js
  functions/api/routes/review/reviewTagListGET.js
  functions/api/routes/user/userListMajorGET.js
  functions/api/routes/user/userMypageAppVersionRecentGET.js
  functions/api/routes/user/userMypageCommentListGET.js
  functions/api/routes/user/userMypageGET.js
  functions/api/routes/user/userMypageLikeListGET.js
  functions/api/routes/user/userMypagePUT.js
  functions/api/routes/user/userMypagePostListGET.js
  functions/api/routes/user/userMypagePostQuestionListGET.js
  functions/api/routes/user/userMypageReviewListGET.js
  functions/lib/errorHandlers.js
  functions/middlewares/slackAPI.js
Labels: feat, refactor

#329 mypage post list, comment list, like list
  functions/api/routes/user/userMypageCommentListGET.js
  functions/api/routes/user/userMypageLikeListGET.js
  functions/api/routes/user/userMypagePostListGET.js
  functions/db/comment.js
  functions/db/post.js
  functions/db/review.js
Labels: feat

#333 mypage question list
  functions/api/routes/user/index.js
  functions/api/routes/user/userMypagePostQuestionListGET.js
  functions/db/post.js
Labels: refactor

#330 my page
  functions/api/routes/user/userMypageGET.js
  functions/db/post.js
Labels: feat

#336 mypage put
  functions/api/routes/user/userMypagePUT.js
  functions/db/user.js
Labels: feat

#310 get banner image list
  functions/api/routes/app/bannerListGET.js
  functions/api/routes/app/index.js
  functions/constants/responseMessage.js
  functions/db/image.js
  functions/db/index.js
Labels: feat

#338 apply change
  .gitignore
  functions/api/routes/review/index.js
  functions/api/routes/review/reviewUniversityListGET.js
  functions/db/review.js
Labels: fix

#337 post get
  functions/api/routes/post/postGET.js
  functions/db/comment.js
  functions/db/post.js
Labels: feat

#339 delete send 204 status code
  functions/api/routes/auth/authUniversityGET.js
  functions/api/routes/major/majorGET.js
  functions/api/routes/user/userMypageReviewListGET.js
  functions/constants/responseMessage.js
Labels: fix

#316 get review of all major of one school
  README.md
  functions/api/routes/review/index.js
  functions/api/routes/review/reviewMajorListPOST.js
  functions/api/routes/review/reviewUniversityListGET.js
  functions/db/review.js
  package-lock.json
Labels: feat

#344 user major list
  functions/api/routes/user/userListMajorGET.js
  functions/db/post.js
  functions/db/user.js
Labels: feat

#350 change appVersionGET endpoint
  functions/api/routes/app/index.js
  functions/api/routes/app/versionRecentGET.js
  functions/api/routes/user/index.js
Labels: fix

#340 sort major list
  functions/api/routes/major/majorListGET.js
  functions/constants/major.js
  functions/db/major.js
Labels: feat

#345 create post, update post
  functions/api/routes/post/postPOST.js
  functions/api/routes/post/postPUT.js
Labels: feat

#349 post list
  functions/api/routes/post/index.js
  functions/api/routes/post/postListGET.js
  functions/db/post.js
Labels: feat

#356 load app version from env
  functions/api/routes/app/versionRecentGET.js
  functions/constants/appVersion.js
Labels: feat

#351 [FIX] change statuscode
  functions/api/routes/auth/authSignupPOST.js
  functions/api/routes/comment/commentPOST.js
  functions/api/routes/post/postPOST.js
  functions/api/routes/report/reportPOST.js
  functions/api/routes/review/reviewPOST.js
Labels: fix

#352 change method of get review list
  functions/api/routes/review/index.js
  functions/api/routes/review/reviewMajorListGET.js
  functions/db/review.js
Labels: fix

#360 [FIX] fix env to uppercase
  functions/api/routes/app/versionRecentGET.js
Labels: fix
