Repository TeamNado-Sunbae/NadoSunbae-Server, pull requests merged in 2022-09, with the labels that each got.

#355 implement post search
  functions/api/routes/post/postListGET.js
  functions/db/post.js
Labels: feat

#361 fix post list
  functions/api/routes/post/index.js
  functions/api/routes/post/postListGET.js
  functions/db/post.js
Labels: fix

#358 init swagger
  .gitignore
  functions/api/routes/auth/authLoginPOST.js
  functions/api/routes/auth/authRenewalTokenPOST.js
  functions/api/routes/auth/authSecessionPOST.js
  functions/api/routes/index.js
  functions/api/routes/major/index.js
  functions/api/routes/review/index.js
  functions/config/swagger/swagger.js
  functions/package-lock.json
  functions/package.json
Labels: feat

#363 refactor swagger
  .gitignore
  functions/api/routes/app/index.js
  functions/api/routes/auth/index.js
  functions/api/routes/block/index.js
  functions/api/routes/comment/index.js
  functions/api/routes/inappropriateReview/index.js
  functions/api/routes/index.js
  functions/api/routes/like/index.js
  functions/api/routes/major/index.js
  functions/api/routes/notification/index.js
  functions/api/routes/post/index.js
  functions/api/routes/report/index.js
  functions/api/routes/review/index.js
  functions/api/routes/user/index.js
  functions/config/swagger.js
  functions/config/swagger/swagger.js
  functions/package-lock.json
  functions/package.json
Labels: refactor

#362 implement sunbae ranking
  functions/api/routes/index.js
  functions/api/routes/user/index.js
  functions/api/routes/user/userListUniversityGET.js
  functions/config/swagger.js
  functions/constants/responseMessage.js
  functions/db/user.js
Labels: feat

#367 separate banner image
  functions/api/routes/app/bannerListGET.js
  functions/api/routes/app/index.js
  functions/db/image.js
Labels: fix

#370 add isAuthorized to postGET res
  functions/api/routes/post/postGET.js
Labels: fix

#371 add update alert text to login res
  functions/api/routes/auth/authLoginPOST.js
Labels: fix

#375 fix route file name
  functions/api/routes/major/index.js
  functions/api/routes/major/majorUniversityListGET.js
  functions/api/routes/post/index.js
  functions/api/routes/post/postUniversityListGET.js
  functions/api/routes/user/index.js
  functions/api/routes/user/userCommentListGET.js
  functions/api/routes/user/userGET.js
  functions/api/routes/user/userLikeListGET.js
  functions/api/routes/user/userMajorListGET.js
  functions/api/routes/user/userPUT.js
  functions/api/routes/user/userPostListGET.js
  functions/api/routes/user/userPostQuestionListGET.js
  functions/api/routes/user/userReviewListGET.js
  functions/api/routes/user/userUniversityListGET.js
Labels: fix

#376 add type check
  functions/api/routes/post/postGET.js
Labels: fix

#377 rename banner, add redirect url
  functions/api/routes/app/bannerListGET.js
  functions/db/banner.js
  functions/db/index.js
Labels: feat

#378 fix comment notification message
  functions/api/routes/comment/commentPOST.js
Labels: fix

#379 refactor review major db query
  functions/api/routes/review/reviewMajorListGET.js
  functions/db/review.js
Labels: refactor

#381 fix error review major list
  functions/db/review.js
Labels: fix

#380 implement favorites
  functions/api/routes/favorites/favoritesPOST.js
  functions/api/routes/favorites/index.js
  functions/api/routes/index.js
  functions/api/routes/major/index.js
  functions/api/routes/major/majorUniversityListGET.js
  functions/constants/responseMessage.js
  functions/db/favorites.js
  functions/db/index.js
  functions/db/major.js
Labels: feat

#383 fix swaager type (string to number)
  functions/api/routes/auth/index.js
  functions/api/routes/block/index.js
  functions/api/routes/comment/index.js
  functions/api/routes/favorites/index.js
  functions/api/routes/inappropriateReview/index.js
  functions/api/routes/like/index.js
  functions/api/routes/major/index.js
  functions/api/routes/notification/index.js
  functions/api/routes/post/index.js
  functions/api/routes/report/index.js
  functions/api/routes/review/index.js
  functions/api/routes/user/index.js
Labels: fix

#386 add answererId to post detail query
  functions/db/post.js
Labels: fix
