Repository TeamNado-Sunbae/NadoSunbae-Server, pull requests merged in 2022-02, with the labels that each got.

#155 [REFACTOR] refactor mypage api
  functions/api/routes/user/index.js
  functions/api/routes/user/userMypageGET.js
  functions/api/routes/user/userMypageOtherGET.js
Labels: ❄️ seol, refactor

#100 [REFACTOR] #76 - 쿼리문 하나로 줄이기
  functions/api/routes/major/majorListGET.js
  functions/db/major.js
Labels: 🦊 juhyeon, refactor

#152 [FIX] user list 랜덤으로 정렬
  functions/api/routes/user/userListMajorGET.js
Labels: bug, ❄️ seol

#162 [FEAT] #161 - 후기삭제 response에 isReviewed 추가
  functions/api/routes/reviewPost/reviewPostDELETE.js
Labels: enhancement, 🦊 juhyeon

#165 [FEAT] #160 - 해당 학교 이메일 조회 구현
  functions/api/routes/auth/authUniversityGET.js
  functions/api/routes/auth/index.js
  functions/constants/responseMessage.js
  functions/db/index.js
  functions/db/university.js
Labels: enhancement, 🦊 juhyeon

#167 [FEAT] #166 - 로그인에 isEmailVerified 추가
  functions/api/routes/auth/authLoginPOST.js
Labels: enhancement, 🦊 juhyeon

#185 [REFACTOR] change variable name notification type to notification typ…
  functions/api/routes/notification/notificationListGET.js
  functions/db/notification.js
Labels: ❄️ seol, refactor

#183 [REFACTOR] 모든 int형 재검토
  functions/api/routes/reviewPost/reviewPostDELETE.js
Labels: ❄️ seol, refactor

#176 [FEAT] #175 - userMypageAppVersionGET
  functions/api/routes/user/index.js
  functions/api/routes/user/userMypageAppVersionRecentGET.js
  functions/constants/appVersion.js
  functions/constants/responseMessage.js
Labels: enhancement, 🦊 juhyeon

#190 [REFACTOR] fix deleted review post response
  functions/api/routes/reviewPost/reviewPostDELETE.js
  functions/db/reviewPost.js
Labels: ❄️ seol, refactor

#191 [FIX] add is reviewed to deleted review post
  functions/api/routes/reviewPost/reviewPostDELETE.js
Labels: bug, ❄️ seol

#196 [FEAT] 삭제된 글, 댓글의 경우 알림리스트 처리
  functions/api/routes/classroomPost/classroomPostPOST.js
  functions/api/routes/comment/commentPOST.js
  functions/api/routes/notification/notificationListGET.js
  functions/db/notification.js
Labels: bug, enhancement, ❄️ seol

#199 [FEAT] add isLiked, refactor post type
  functions/api/routes/classroomPost/classroomPostMajorListGET.js
  functions/api/routes/reviewPost/reviewPostListPOST.js
  functions/api/routes/user/userMypageClassroomPostListGET.js
Labels: enhancement, ❄️ seol

#158 [FEAT] #149 - login에 refresh 구현
  functions/api/routes/auth/authLoginPOST.js
  functions/api/routes/auth/authLoginTokenPOST.js
  functions/api/routes/auth/authRenewalTokenPOST.js
  functions/api/routes/auth/authSignupPOST.js
  functions/api/routes/auth/index.js
  functions/constants/responseMessage.js
  functions/db/user.js
  functions/lib/jwtHandlers.js
Labels: enhancement, 🦊 juhyeon

#178 [FEAT] #177 - 회원가입 메일 전송 로직 추가
  functions/api/routes/auth/authSignupPOST.js
  functions/constants/responseMessage.js
Labels: enhancement, 🦊 juhyeon

#187 [FIX] #186 - 학과 전체 조회 때 미진입 안보이게 shift 추가
  functions/api/routes/major/majorListGET.js
Labels: bug, 🦊 juhyeon

#200 [FEAT] #179 - authCertificationEmailPOST
  functions/api/routes/auth/authCertificationEmailPOST.js
  functions/api/routes/auth/index.js
Labels: enhancement, 🦊 juhyeon

#180 [FEAT] #173 - userMypagePUT
  functions/api/routes/user/index.js
  functions/api/routes/user/userMypagePUT.js
  functions/db/user.js
Labels: enhancement, 🌺 eunji

#201 [FEAT] #192 - 1:1 질문글 답변자 삭제 권한 수정
  functions/api/routes/classroomPost/classroomPostDELETE.js
Labels: bug, ❄️ seol

#188 [FEAT] #172 - userMypageCommentListGET
  functions/api/routes/user/index.js
  functions/api/routes/user/userMypageCommentListGET.js
  functions/db/classroomPost.js
  functions/db/comment.js
Labels: enhancement, 🌺 eunji

#170 [FEAT] #168 - userMypageReviewPostListGET
  functions/api/routes/user/index.js
  functions/api/routes/user/userMypageReviewPostListGET.js
  functions/db/reviewPost.js
Labels: enhancement, 🦊 juhyeon

#214 [REFACTOR] #213 - 회원가입 속도 개선
  functions/api/routes/auth/authSignupPOST.js
Labels: 🦊 juhyeon, refactor

#212 [FEAT] implement reset password
  functions/api/routes/auth/authResetPasswordPOST.js
  functions/api/routes/auth/index.js
  functions/constants/responseMessage.js
Labels: enhancement, ❄️ seol

#215 [FEAT] #206 - blockPOST
  functions/api/routes/block/blockPOST.js
  functions/api/routes/block/index.js
  functions/api/routes/index.js
  functions/constants/responseMessage.js
  functions/db/block.js
  functions/db/index.js
Labels: enhancement, 🌺 eunji

#217 [FIX] fix like sorting
  functions/api/routes/classroomPost/classroomPostMajorListGET.js
  functions/api/routes/reviewPost/reviewPostListPOST.js
  functions/api/routes/user/userMypageClassroomPostListGET.js
Labels: bug, ❄️ seol

#222 [REFACTOR] get others mypage review post list
  functions/api/routes/user/index.js
  functions/api/routes/user/userMypageReviewPostListGET.js
Labels: bug, ❄️ seol, refactor

#223 [STYLE] modify function name
  functions/api/routes/block/blockPOST.js
  functions/db/block.js
Labels: 🌺 eunji

#203 [FEAT] #202 - userMypageCommentListGET
  functions/api/routes/user/index.js
  functions/api/routes/user/userMypageCommentListGET.js
  functions/db/comment.js
Labels: enhancement, 🌺 eunji

#224 [STYLE] 알림 리스트에서 원본글이나 댓글이 삭제됐을 경우 워딩 변경
  functions/api/routes/notification/notificationListGET.js
Labels: ❄️ seol, refactor

#218 [FEAT] #207 - blockListGET
  functions/api/routes/block/blockListGET.js
  functions/api/routes/block/index.js
  functions/constants/responseMessage.js
  functions/db/block.js
Labels: enhancement, 🌺 eunji

#229 [FIX] fix conditional statement
  functions/api/routes/reviewPost/reviewPostDELETE.js
Labels: bug, ❄️ seol

#227 [FIX] #226 - 마이페이지 닉네임 관련 분기 처리 추가
  functions/api/routes/user/userMypagePUT.js
  functions/db/user.js
Labels: bug, 🌺 eunji

#234 [REFACTOR] #233 - postTypeDB 지우고 constants 사용
  functions/api/routes/classroomPost/classroomPostInformationGET.js
  functions/api/routes/classroomPost/classroomPostQuestionGET.js
  functions/db/index.js
  functions/db/postType.js
Labels: 🌺 eunji, refactor

#231 [REFACTOR] 알림 리펙토링
  functions/api/routes/classroomPost/classroomPostPOST.js
  functions/api/routes/comment/commentPOST.js
  functions/db/comment.js
  functions/db/user.js
  functions/lib/pushAlarmHandlers.js
Labels: ❄️ seol, 🌺 eunji, refactor

#235 [FEAT] #211 - authLogoutPOST
  functions/api/routes/auth/authLogoutPOST.js
  functions/api/routes/auth/index.js
  functions/constants/responseMessage.js
  functions/db/user.js
Labels: enhancement, 🌺 eunji

#205 [FEAT] 신고 기능
  functions/api/routes/auth/authLoginPOST.js
  functions/api/routes/classroomPost/classroomPostInformationGET.js
  functions/api/routes/classroomPost/classroomPostPOST.js
  functions/api/routes/classroomPost/classroomPostQuestionGET.js
  functions/api/routes/report/index.js
  functions/api/routes/report/reportCommentPOST.js
  functions/api/routes/report/reportPOST.js
  functions/api/routes/report/reportPUT.js
  functions/api/routes/report/reportPostPOST.js
  functions/api/routes/report/reportUserPOST.js
  functions/api/routes/reviewPost/reviewPostDetailGET.js
  functions/api/routes/reviewPost/reviewPostPOST.js
  functions/constants/reportPeriodType.js
  functions/constants/reportType.js
  functions/constants/responseMessage.js
  functions/db/classroomPost.js
  functions/db/comment.js
  functions/db/index.js
  functions/db/report.js
  functions/db/reviewPost.js
  functions/db/user.js
Labels: enhancement, ❄️ seol

#239 [FEAT] 차단 로직 베이스 코드 추가
  functions/api/routes/classroomPost/classroomPostMajorListGET.js
  functions/db/block.js
  functions/db/classroomPost.js
Labels: enhancement, ❄️ seol

#241 [FEAT] 신고 리펙토링(dateHandlers 생성 및 dayjs 사용), 신고 알럿 변경사항 반영
  functions/api/routes/auth/authLoginPOST.js
  functions/api/routes/classroomPost/classroomPostInformationGET.js
  functions/api/routes/classroomPost/classroomPostPOST.js
  functions/api/routes/classroomPost/classroomPostQuestionGET.js
  functions/api/routes/report/reportPUT.js
  functions/api/routes/reviewPost/reviewPostDetailGET.js
  functions/api/routes/reviewPost/reviewPostPOST.js
  functions/lib/dateHandlers.js
Labels: enhancement, ❄️ seol, refactor

#236 [FEAT] 좋아요 목록
  functions/api/routes/classroomPost/classroomPostMajorListGET.js
  functions/api/routes/user/index.js
  functions/api/routes/user/userMypageLikeListGET.js
  functions/constants/responseMessage.js
  functions/db/classroomPost.js
  functions/db/reviewPost.js
Labels: enhancement, ❄️ seol

#249 [STYLE] #248 - 쿼리 TRUE, FALSE 수정
  functions/db/classroomPost.js
  functions/db/comment.js
  functions/db/notification.js
  functions/db/relationReviewPostTag.js
  functions/db/report.js
  functions/db/reviewPost.js
  functions/db/tag.js
  functions/db/user.js
Labels: 🌺 eunji, refactor

#244 [FEAT] #210 - authSecessionDELETE
  functions/api/routes/auth/authLoginPOST.js
  functions/api/routes/auth/authSecessionDELETE.js
  functions/api/routes/auth/index.js
  functions/constants/responseMessage.js
  functions/db/block.js
  functions/db/classroomPost.js
  functions/db/comment.js
  functions/db/like.js
  functions/db/notification.js
  functions/db/report.js
  functions/db/reviewPost.js
  functions/db/user.js
Labels: enhancement, 🌺 eunji

#251 [REFACTOR] get post type from constants
  functions/api/routes/classroomPost/classroomPostPOST.js
  functions/api/routes/comment/commentPOST.js
  functions/api/routes/reviewPost/reviewPostDetailGET.js
  functions/api/routes/reviewPost/reviewPostPUT.js
Labels: ❄️ seol, refactor

#250 [FEAT] read all notification when post id, receiver id is same
  functions/api/routes/notification/notificationReadPUT.js
  functions/db/notification.js
Labels: enhancement, ❄️ seol

#252 [REMOVE] #174 - 사용하지 않은 lodash 및 db import 삭제
  functions/api/routes/classroomPost/classroomPostPUT.js
  functions/api/routes/comment/commentPUT.js
  functions/api/routes/reviewPost/reviewPostPOST.js
  functions/db/image.js
  functions/db/like.js
  functions/db/major.js
  functions/db/tag.js
Labels: 🦊 juhyeon, refactor

#253 [FEAT] prevent invisible users from showing in list, count, alarm
  functions/api/routes/classroomPost/classroomPostInformationGET.js
  functions/api/routes/classroomPost/classroomPostMajorListGET.js
  functions/api/routes/classroomPost/classroomPostQuestionGET.js
  functions/api/routes/comment/commentPOST.js
  functions/api/routes/notification/notificationListGET.js
  functions/api/routes/user/userListMajorGET.js
  functions/api/routes/user/userMypageClassroomPostListGET.js
  functions/api/routes/user/userMypageClassroomPostQuestionListGET.js
  functions/api/routes/user/userMypageCommentListGET.js
  functions/api/routes/user/userMypageGET.js
  functions/api/routes/user/userMypageLikeListGET.js
  functions/db/classroomPost.js
  functions/db/comment.js
  functions/db/like.js
  functions/db/notification.js
  functions/db/reviewPost.js
  functions/db/user.js
Labels: enhancement, ❄️ seol

#255 [FIX] fix conditional statement when list empty
  functions/api/routes/classroomPost/classroomPostMajorListGET.js
  functions/api/routes/major/majorListGET.js
  functions/api/routes/report/reportPUT.js
  functions/api/routes/reviewPost/reviewPostBackgroundImageListGET.js
  functions/api/routes/reviewPost/reviewPostListPOST.js
  functions/api/routes/user/userMypageCommentListGET.js
  functions/api/routes/user/userMypageReviewPostListGET.js
Labels: bug, ❄️ seol

#256 [FEAT] #208 - add block to reviewpost list get
  functions/api/routes/reviewPost/reviewPostListPOST.js
  functions/db/reviewPost.js
Labels: enhancement, 🦊 juhyeon

#259 [FIX] #258 - 질문글 상세 조회 createdAt -> updatedAt 수정
  functions/api/routes/classroomPost/classroomPostQuestionGET.js
Labels: 🦊 juhyeon

#261 [FIX] fix created at to review post timestamp
  functions/api/routes/reviewPost/reviewPostListPOST.js
  functions/db/reviewPost.js
Labels: bug, ❄️ seol

#254 [FEAT] 부적절 후기
  functions/api/routes/auth/authLoginPOST.js
  functions/api/routes/classroomPost/classroomPostInformationGET.js
  functions/api/routes/classroomPost/classroomPostPOST.js
  functions/api/routes/classroomPost/classroomPostQuestionGET.js
  functions/api/routes/inappropriateReviewPost/inappropriateReviewPostPOST.js
  functions/api/routes/inappropriateReviewPost/index.js
  functions/api/routes/index.js
  functions/api/routes/reviewPost/reviewPostDELETE.js
  functions/api/routes/reviewPost/reviewPostDetailGET.js
  functions/api/routes/reviewPost/reviewPostPOST.js
  functions/constants/responseMessage.js
  functions/db/inappropriateReviewPost.js
  functions/db/index.js
  functions/db/reviewPost.js
  functions/middlewares/auth.js
Labels: enhancement, ❄️ seol

#263 [REFACTOR] delete code about image url, add error handling
  functions/api/routes/reviewPost/index.js
  functions/api/routes/reviewPost/reviewPostBackgroundImageListGET.js
  functions/api/routes/reviewPost/reviewPostDetailGET.js
  functions/api/routes/reviewPost/reviewPostPOST.js
  functions/api/routes/reviewPost/reviewPostPUT.js
  functions/constants/backgroundImage.js
  functions/db/image.js
  functions/db/index.js
Labels: bug, ❄️ seol, refactor

#267 [FEAT] implement mypage app information link
  functions/api/routes/app/appLinkGET.js
  functions/api/routes/app/index.js
  functions/api/routes/index.js
  functions/constants/responseMessage.js
Labels: enhancement, ❄️ seol

#270 [FIX] notification error handling
  functions/api/routes/notification/notificationDELETE.js
  functions/api/routes/notification/notificationListGET.js
Labels: bug, ❄️ seol
